apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
data:
  IMAGE_URL: "/image_url"
  DBHOST: "e-mysql"
  DBPORT: "3306"
  GROUP_NAME: "GROUP11"
  IMAGE_S3: "https://background-image-clo835.s3.amazonaws.com/"
  image : |
    {
      "backgroundimg1" : "https://background-image-clo835.s3.amazonaws.com/sample.jpg"
    }
